-- MySQL schema for Semarang Flood Dashboard (prototype)

CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('ADMIN','PETUGAS') NOT NULL DEFAULT 'PETUGAS',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS areas (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  type ENUM('KECAMATAN','KELURAHAN') NOT NULL,
  adm4_code VARCHAR(20) NULL,
  parent_area_id BIGINT NULL,
  INDEX idx_adm4 (adm4_code),
  FOREIGN KEY (parent_area_id) REFERENCES areas(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS water_stations (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  source VARCHAR(120) NOT NULL DEFAULT 'pantaubanjir.semarangkota.go.id',
  min_cm INT NOT NULL DEFAULT 0,
  max_cm INT NOT NULL DEFAULT 500,
  siaga_cm INT NULL,
  awas_cm INT NULL
);

CREATE TABLE IF NOT EXISTS water_level_readings (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  station_id BIGINT NOT NULL,
  reading_time DATETIME NOT NULL,
  level_cm INT NOT NULL,
  status_text VARCHAR(30) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_station_time (station_id, reading_time),
  FOREIGN KEY (station_id) REFERENCES water_stations(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS weather_forecasts (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  area_id BIGINT NOT NULL,
  analysis_time_utc DATETIME NULL,
  forecast_time_local DATETIME NOT NULL,
  t_c FLOAT NULL,
  hu_pct FLOAT NULL,
  tcc_pct FLOAT NULL,
  ws_kmh FLOAT NULL,
  wd VARCHAR(10) NULL,
  weather_desc VARCHAR(60) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_area_time (area_id, forecast_time_local),
  FOREIGN KEY (area_id) REFERENCES areas(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS cctv_sources (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  hls_url TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS flood_polygons (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  area_id BIGINT NOT NULL,
  geojson LONGTEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (area_id) REFERENCES areas(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS risk_points (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(160) NOT NULL,
  zone ENUM('BARAT','TIMUR','TENGAH','UTARA') NOT NULL,
  lat DOUBLE NOT NULL,
  lng DOUBLE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE water_stations
  ADD COLUMN zone ENUM('BARAT','TIMUR','TENGAH','UTARA','UTARA_TIMUR','LAINNYA') NULL,
  ADD COLUMN kind ENUM('SUNGAI','BENDUNGAN') NOT NULL DEFAULT 'SUNGAI',
  ADD COLUMN lat DOUBLE NULL,
  ADD COLUMN lng DOUBLE NULL;

ALTER TABLE cctv_sources
  ADD COLUMN category ENUM('SUNGAI','GENANGAN') NOT NULL DEFAULT 'SUNGAI',
  ADD COLUMN lat DOUBLE NULL,
  ADD COLUMN lng DOUBLE NULL;